### PR TITLE
Command loading

### PR DESCRIPTION
**Pull request by NthPortal**

### CODE REVIEW

**Comment by NthPortal** [comment]
It seems a couple commits got duplicated because of a bad rebase or something?

**Comment by Thelonedevil** [comment]
hmmm odd O_o

**Comment by NthPortal** [comment]
As far as I can tell, they're identical. Just with different histories or something, so they have different hashes. Not really sure why.

**Comment by Thelonedevil** [comment]
wait did you merge a branch into itself? or am i reading that merge commit wrong?

**Comment by NthPortal** [comment]
Um... yeah, there was a merge conflict between local and remote. Basically, the second to last commit was based on the 2 local commits, which (for some reason) didn't match the remote commits, so there was a conflict in which I basically dropped anything the remote wanted to add.

**Comment by Thelonedevil** [comment]
Do you want to see if there is an easy way to fix the history or shall i just merge it?

**Comment by NthPortal** [comment]
You can if you want, but I can't be bothered, tbh.

**Pull request merged**
