### PR TITLE
Fixed connecting to Twitch.

### PR DESCRIPTION
**Pull request by NthPortal**

### CODE REVIEW

**Comment by Thelonedevil** [comment]
When did this even break?

**Comment by NthPortal** [comment]
When I did the restructuring where I added `TwitchBot` and moved most of the code from `IRCBot` into it, I apparently missed this reference. (And don't worry, I did a search for other references before committing.)

**Comment by NthPortal** [comment]
Apparently none of our dev build users (dminer and, uh... everyone else >.>) use Twitch.

**Comment by NthPortal** [comment]
Twitch seems to be giving an error message for `TWITCHCLIENT 3` (or `2`), and I'm not sure why.

**Comment by Thelonedevil** [comment]
Looks like it was deprecated in [may](https://discuss.dev.twitch.tv/t/notice-of-upcoming-changes-deprecating-the-twitchclient-command/2270)  we need to change it for [this](https://github.com/justintv/Twitch-API/blob/master/IRC.md#twitch-capabilities)

**Comment by NthPortal** [comment]
Do you wanna figure out what it is we need and PR it to my branch?

**Comment by Thelonedevil** [comment]
I'll probably look at it tomorrow

**Comment by NthPortal** [comment]
See #307

**Pull request closed without merging**
