### PR TITLE
Added [[countof{{command}}]] parser term.

### PR DESCRIPTION
**Pull request by NthPortal**
Allows you to have counter commands which can be read without incrementing their count.

### CODE REVIEW

**Comment by NthPortal** [comment]
@Thelonedevil Do you think the last 2 commits are useful/necessary?

**Comment by Thelonedevil** [comment]
I would say that they are probably not strictly necessary, but I think we should keep them just in case.

**Comment by NthPortal** [comment]
I mean, if the command name is empty, then `Commands.get()` will return an empty optional. Essentially, it's a small optimization of not making a database call if the user is doing it wrong, and I'm not sure if that makes sense.

**Comment by Thelonedevil** [comment]
Well database calls cost IO so a small stream probbly wouldnt notice it, but a large streamer might if its setup wrong

**Comment by NthPortal** [comment]
I mean, only if you're spamming the command. Like, the cost is only incurred if you do `[[countof{{}}]]` (or `[[countof]]`), which won't work properly anyway. If the term is used properly, the check is useless and... kinda makes the code messier/uglier.
Idk.

**Comment by NthPortal** [comment]
I mean, I think a lot of it is that I find it concerning that there are now 3 layers of `if` statements.

**Comment by NthPortal** [comment]
Updated to remove last 2 commits

**Pull request merged**
