### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Thelonedevil**

### CODE REVIEW

**Comment by NthPortal** [comment]
Should this be merged into master?

**Comment by Thelonedevil** [comment]
the first commit should have been... i made an oops there... The first commit fixes the changed host, and teh second fixes the dev versions to the new group and artifact and stuff, might be a good idea to merge both into master actually, since they are the new dev builds...

**Comment by Thelonedevil** [comment]
Only problem is that the current ReadMe-Update branch has all the new dev changes...

**Comment by NthPortal** [comment]
Redo it based on master, and then PR it there. Also, you might be able to PR master to dev afterward (I think?)

**Comment by Thelonedevil** [comment]
See #377

**Pull request closed without merging**
